Furniture/furniture_site/furniture_app/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('product/', FurnitureHome.as_view(), name='furniture'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('account/<int:pk>/', ShowProfilePageView.as_view(), name='user_profile'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('category/<slug:category_slug>/', ProductCategory.as_view(), name='category'),
    path('product/<slug:product_slug>', ShowProduct.as_view(), name='product'),
    path('edit_profile/', edit, name='edit_profile'),
]

Furniture/furniture_site/furniture_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('furniture_app.urls')),
    path('', include('orders.urls')),
    path('', include('landing.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Furniture/furniture_site/orders/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path(r'cart_adding/', cart_adding, name='cart_adding'),
    path(r'checkout/', checkout, name='checkout'),
]

Furniture/furniture_site/furniture_app/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название категории")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'category_slug': self.slug})


class Product(models.Model):
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name="Название")
    description = models.TextField(verbose_name="Описание", null=True, default=None)
    characters = models.TextField(verbose_name="Характеристики", blank=True, null=True, default=None)
    short_description = models.TextField(verbose_name="Краткое описание", blank=True, null=True, default=None)
    image = models.ImageField(upload_to='products_images/main/', verbose_name="Изображение")
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Цена")
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    class Meta:
        verbose_name = "Мебель"
        verbose_name_plural = "Мебель"
        ordering = ['id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('furniture', kwargs={'product_slug': self.slug})


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, verbose_name="Товар", on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='products_images/', verbose_name="Фотография")
    is_main = models.BooleanField(default=False, verbose_name="Основная")
    is_additional = models.BooleanField(default=False, verbose_name="Дополнительная")
    is_active = models.BooleanField(default=True, verbose_name="Активна")
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Создана")
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name="Изменена")

    def __str__(self):
        return "%s" % self.pk

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'


class Customer(models.Model):
    user = models.OneToOneField(User, verbose_name="Покупатель", on_delete=models.CASCADE)
    name = models.CharField(max_length=64, blank=True, null=True, default=None, verbose_name="Имя пользователя")
    lastname = models.CharField(max_length=64, blank=True, null=True, default=None, verbose_name="Фамилия пользователя")
    email = models.EmailField(blank=True, null=True, default=None, verbose_name="Почта")
    phone = models.CharField(max_length=48, blank=True, null=True, default=None, verbose_name="Номер телефона")
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        verbose_name = "Покупатель"
        verbose_name_plural = "Покупатель"

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)

Furniture/furniture_site/orders/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from utils.main import disable_for_loaddata

from furniture_app.models import *

User = get_user_model()


class Status(models.Model):
    name = models.CharField(max_length=24, blank=True, null=True, default=None, verbose_name="Статус заказа")
    is_active = models.BooleanField(default=True, verbose_name="Активен")
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Создан")
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name="Изменен")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Статус заказа'
        verbose_name_plural = 'Статусы заказа'


class Order(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, default=None, verbose_name="Пользователь", on_delete=models.CASCADE)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Общая цена") #total price for all products in order
    customer_name = models.CharField(max_length=64, blank=True, null=True, default=None, verbose_name="Имя пользователя")
    customer_lastname = models.CharField(max_length=64, blank=True, null=True, default=None, verbose_name="Фамилия пользователя")
    customer_email = models.EmailField(blank=True, null=True, default=None, verbose_name="Почта")
    customer_phone = models.CharField(max_length=48, blank=True, null=True, default=None, verbose_name="Номер телефона")
    customer_address = models.CharField(max_length=128, blank=True, null=True, default=None, verbose_name="Адрес")
    comments = models.TextField(blank=True, null=True, default=None, verbose_name="Пожелание")
    status = models.ForeignKey(Status, verbose_name="Статус", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Создан")
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name="Изменен")

    def __str__(self):
        return "Заказ %s %s" % (self.pk, self.status.name)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def save(self, *args, **kwargs):

        super(Order, self).save(*args, **kwargs)


class ProductInOrder(models.Model):
    order = models.ForeignKey(Order, blank=True, null=True, default=None, verbose_name="Заказ", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=True, null=True, default=None, verbose_name="Продукт", on_delete=models.CASCADE)
    count = models.IntegerField(default=1, verbose_name="Количество")
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Цена за единицу")
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Общая цена")
    is_active = models.BooleanField(default=True, verbose_name="Активен")
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Создан")
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name="Изменен")

    def __str__(self):
        return "%s" % self.product.title

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        print(self.count)

        self.total_price = int(self.count) * price_per_item

        super(ProductInOrder, self).save(*args, **kwargs)


@disable_for_loaddata
def product_in_order_post_save(sender, instance, created, **kwargs):
    order = instance.order
    all_products_in_order = ProductInOrder.objects.filter(order=order, is_active=True)

    order_total_price = 0
    for item in all_products_in_order:
        order_total_price += item.total_price

    instance.order.total_price = order_total_price
    instance.order.save(force_update=True)


post_save.connect(product_in_order_post_save, sender=ProductInOrder)


class ProductInCart(models.Model):
    session_key = models.CharField(max_length=128, blank=True, null=True, default=None)
    order = models.ForeignKey(Order, blank=True, null=True, default=None, verbose_name="Заказ", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, blank=True, null=True, default=None, verbose_name="Продукт", on_delete=models.CASCADE)
    count = models.PositiveIntegerField(default=1, verbose_name="Количество")
    price_per_item = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Цена за единицу")
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="Общая цена")
    is_active = models.BooleanField(default=True, verbose_name="Активен")
    created = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name="Создан")
    updated = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name="Изменен")

    def __str__(self):
        return "%s" % self.product.title

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'

    def save(self, *args, **kwargs):
        price_per_item = self.product.price
        self.price_per_item = price_per_item
        self.total_price = int(self.count) * price_per_item

        super(ProductInCart, self).save(*args, **kwargs)

Furniture/furniture_site/furniture_app/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class ResisterUserForm(UserCreationForm):
    username = forms.CharField(label='Номер телефона', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ("username", 'email', "password1", "password2")


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Номер телефона', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserEditForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        widget=forms.TextInput(
            attrs={'placeholder': 'Имя', 'class': 'form-control'}
        )
    )

    last_name = forms.CharField(
        min_length=2,
        widget=forms.TextInput(
            attrs={'placeholder': 'Имя', 'class': 'form-control'}
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'placeholder': 'Email', 'class': 'form-control'}
        )
    )

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

Furniture/furniture_site/furniture_app/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from orders.models import Order
from .forms import *
from .utils import *


class FurnitureHome(DataMixin, ListView):
    template_name = 'furniture_app/all_products.html'
    context_object_name = 'products'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Мебель')
        context = dict(list(context.items()) + list(c_def.items()))
        return context


class ProductCategory(DataMixin, ListView):
    template_name = 'furniture_app/all_products.html'
    context_object_name = 'products'

    def get_queryset(self):
        return Product.objects.filter(category__slug=self.kwargs['category_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Категория - ' + str(context['products'][0].category))
        context = dict(list(context.items()) + list(c_def.items()))
        return context


class ShowProduct(DataMixin, DetailView):
    template_name = 'furniture_app/furniture.html'
    slug_url_kwarg = 'product_slug'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=context['product'])
        context = dict(list(context.items()) + list(c_def.items()))
        return context


class RegisterUser(DataMixin, CreateView):
    form_class = ResisterUserForm
    template_name = 'furniture_app/register.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация")
        context = dict(list(context.items()) + list(c_def.items()))
        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'furniture_app/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        context = dict(list(context.items()) + list(c_def.items()))
        return context

    def get_success_url(self):
        return reverse_lazy('home')


class ShowProfilePageView(DataMixin, DetailView):
    model = User
    template_name = 'furniture_app/user_profile.html'
    context_object_name = 'user'

    def get_context_data(self, *args, **kwargs):
        users = User.objects.all()
        context = super(ShowProfilePageView, self).get_context_data(*args, **kwargs)
        page_user = get_object_or_404(User, id=self.kwargs['pk'])
        user_order = Order.objects.all()
        c_def = self.get_user_context(title="Профиль")
        context['page_user'] = page_user
        context['users'] = users
        context['user_order'] = user_order
        context = dict(list(context.items()) + list(c_def.items()))
        return context


@login_required
def edit(request):
    context = {

    }
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        if user_form.is_valid():
            user_form.save()
            context = {'success': 1,
                       'menu': menu,
                       'title': 'Настройки',
                       }
            # return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        user_form = UserEditForm(instance=request.user)
        context['user_form'] = user_form
        context['menu'] = menu
        context['title'] = "Контакты"

    return render(request, 'furniture_app/edit_profile.html', context=context)


def logout_user(request):
    logout(request)
    return redirect('login')

# def main_product(request):
#     products_images = ProductImage.objects.filter(is_active=True, is_main=True)
#     categories = Category.objects.all()
#     context = {
#         'menu': menu,
#         'title': 'Мебель',
#         'categories': categories,
#         'products_images': products_images,
#         'login_page': login_page,
#         'cart_page': cart_page
#         }
#     return render(request, 'furniture_app/all_products.html', context=context)


# def show_category(request, category_slug):
#     products = Product.objects.filter(slug=category_slug)
#     categories = Category.objects.all()
#     context = {
#         'menu': menu,
#         'title': 'Мебель',
#         'products': products,
#         'categories': categories,
#         'category_selected': category_slug,
#     }
#     return render(request, 'furniture_app/all_products.html', context=context)


# def show_product(request, product_slug):
#     product = get_object_or_404(ProductImage, slug=product_slug)
#
#     context = {
#         'menu': menu,
#         'product': product,
#         'title': product.title,
#         'category_selected': product.category_id,
#     }
#
#     return render(request, 'furniture_app/furniture.html', context=context)

Furniture/furniture_site/templates/furniture_app/all_products.html
{% extends 'furniture_app/base.html'%}

{% block select %}
        <div class="select-category container-fluid px-lg-5 btn-group" role="group" aria-label="Basic radio toggle button group">
            {% for c in categories %}
                        <input type="radio" class="btn-check" name="btnradio" id="btnradio{{c.slug}}" autocomplete="off">
                        <label class="btn btn-secondary category-items" for="btnradio{{c.slug}}"><a class="nav-item" href="{{ c.get_absolute_url }}">{{c.name}}</a></label>
                {% endfor %}
        </div>
{% endblock %}

{% block content %}

        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-3">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for p in products %}
                    <div class="col mb-2">
                      <div class="card h-100 shadow-sm">
                          {% if p.image %}
                            <a href="{% url 'product' p.slug %}"><img class="card-img-top" src="{{ p.image.url }}" alt="..." /></a>
                          {% endif %}

                        <div class="card-body">
                            <a href="{% url 'product' p.slug %}"><h5 class="fw-bolder">{{p.title}}</h5></a>
                            <p> {{p.price}} ₽</p>
                          <p class="card-text">{{ p.short_description }}</p>
                          <div class="d-flex justify-content-between align-items-center">

                              <button type="button" class="btn btn-sm btn-outline-secondary">
                                  <a class="product-link" href="{% url 'product' p.slug %}">О товаре <i class="bi bi-arrow-right"></i></a>
                              </button>

                          </div>
                        </div>
                      </div>
                    </div>
                {% endfor %}
              </div>
            </div>
        </section>
{% endblock %}

Furniture/furniture_site/templates/furniture_app/basket.html
 <ul class="cart-product nav navbar-nav navbar-right">
        <li>
            <div class="cart-container">
                <a class= "new-order" href="{% url 'checkout'  %}">
                    <button class="cart-button btn-outline-light" type="submit">
                        <i class="bi bi-bag"></i>
                        <span id="cart_total_amount"></span><span id="cart_total_count">
                        {% if products_total_count %}
                            ({{ products_total_count }})
                        {% else %}
                            (0)
                        {% endif %}
                        </span>
                    </button>
                </a>
                <div class="cart-items hidden">
                        <ul class="">
                            {% for product_in_cart in products_in_cart %}
                                <li>
                                    <div class="cart-elements mt-2">
                                        <span class="title-item">
                                            {{ product_in_cart.product.title }}
                                        </span>
                                        <span class="count-item">
                                            {{ product_in_cart.count }} шт.
                                        </span>
                                        <span class="price-item">
                                            {{ product_in_cart.price_per_item }} ₽
                                        </span>
                                         <a class="delete-item" href="" data-product_id="{{ product_in_cart.id }}"><i class="bi bi-x-lg"></i></a>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>

                        <div class="mt-2">
                            <a class= "new-order" href="{% url 'checkout'  %}">
                                Оформить заказ
                            </a>
                        </div>

                </div>
            </div>
        </li>
  </ul>

Furniture/furniture_site/templates/furniture_app/furniture.html
{% extends 'furniture_app/base.html'%}

{% block content %}
     <div class="margin-furniture container px-4">
         <div class="row g-5 mb-5">
             <div class="col-md-6">
                 <div class="col mb-2">
                    <div class="card h-100">
                        <!-- Item image-->
                        <div id="carouselExampleControls" class="carousel carousel-dark slide" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                {% for i in product.productimage_set.all %}
                                    {% if i.image and i.is_main and i.is_active %}
                                    <div class="carousel-item active" data-bs-interval="10000">
                                          <img class="card-img-top" src="{{i.image.url}}" alt="..." />
                                    </div>
                                    {% endif %}
                                    {% if i.image and i.is_additional %}
                                    <div class="carousel-item" data-bs-interval="10000">
                                          <img class="card-img-top" src="{{i.image.url}}" alt="..." />
                                    </div>
                                    {% endif %}
                                {% endfor %}
                            </div>

                            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Предыдущая</span>
                            </button>
                            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Следующая</span>
                            </button>
                        </div>
                    </div>

                </div>
             </div>
             <div class="col-md-6">
                 <div class="col">
                    <h2>{{ product.title }} <img class="ar-icon" src="/media/main_images/ar-icon.png" alt=""></h2>
                         <p class="h5">    Посмотрите на товар в дополненной реальности</p>
                     <a href="/media/komod.usdz" class="ar-link hidden">
                         <p class="lead fw-normal mb-0">Посмотрите в дополненной реальности <i class="bi bi-chevron-right"></i></p>
                     </a>
                     <p class="ar-help hidden">Откройте эту страницу в браузере телефона или планшета</p>
                    <div class="p-3 bg-light mt-3">
                        <p class="h5">Цена: {{ product.price }} </p>
<!--                        <p>{{ product.slug }}</p>-->
                    </div>
                 <div class="p-3 bg-light">
                     <ul class="nav nav-tabs" id="myTab" role="tablist">
                          <li class="nav-item" role="presentation">
                            <button class="nav-link active" id="desc-tab" data-bs-toggle="tab" data-bs-target="#desc" type="button" role="tab" aria-controls="home" aria-selected="true">Описание</button>
                          </li>
                          <li class="nav-item" role="presentation">
                            <button class="product-character nav-link" id="short_desc-tab" data-bs-toggle="tab" data-bs-target="#short_desc" type="button" role="tab" aria-controls="profile" aria-selected="false">Характеристики</button>
                          </li>
                          <li class="nav-item" role="presentation">
                            <button class="product-character nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Дополнительно</button>
                          </li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                          <div class="tab-pane fade show active" id="desc" role="tabpanel" aria-labelledby="home-tab"><p class="mt-3">{{ product.description }}</p></div>
                          <div class="tab-pane fade" id="short_desc" role="tabpanel" aria-labelledby="short_desc-tab"><p class="mt-3">{{ product.characters }}</p></div>
                          <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
                        </div>
                 </div>
                    <div class="mt-2 mb-4">
                        <form id="form_buying_product" class="form-inline" action="{% url 'cart_adding' %}">{% csrf_token %}
                                <div class="form-group d-grid gap-2 d-sm-flex">
                                     <input type="number" class="form-control" name="count" id="count" min="1" max="50" value="1">
                                    <div class="form-group">
                                        <button type="submit" id="submit_btn" class="btn btn-success btn-buy"
                                            data-product_id = "{{ product.id }}"
                                            data-title ="{{ product.title }}"
                                            data-price ="{{ product.price }}">
                                            Купить
                                        </button>
                                    </div>
                                </div>
                            </form>
                    </div>
                </div>
            </div>
         </div>
     </div>
{% endblock %}

Furniture/furniture_site/templates/furniture_app/login.html
{% extends 'furniture_app/base.html'%}

{% block content %}
    <div class="login-page text-center mx-auto">
        <h1 class="mt-3 text-center">{{ title }}</h1>
        <main class="form-signin mt-4">
          <form method="post" class="mb-3">
              {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>
              {% for f in form %}
                <div class="form-floating mb-2">
<!--                  <input class="form-control" id="floatingInput" placeholder="89214345676">-->
                    {{ f }}
                  <label class="form-label" for="{{f.id_for_label}}">{{f.label}}</label>
                </div>
              {% endfor %}
            <button class="mt-3 w-100 btn btn-lg btn-primary" type="submit">Войти</button>
          </form>
            <a href="{% url 'register' %}" role="button">Регистрация</a>
        </main>
    </div>

{% endblock %}

Furniture/furniture_site/templates/furniture_app/message.html
Приветствую!

Новое сообщение с сайта.
Имя: {{ first_name }}
Фамилия: {{ last_name }}
Номер телефона: {{ phone_number }}
Email: {{ email }}
Сообщение: {{ message }}

Furniture/furniture_site/templates/furniture_app/user_profile.html
{% extends 'furniture_app/base.html'%}

{% block content %}

    <div class="margin-page container px-4 text-center px-lg-5">
        <div class="col-sm-12 col-lg-offset-2">
            <h1 class="text-align-center">Профиль</h1>
            <div class="row gx-5 mt-3">
                <div class="col">
                 <div class="p-3 bg-light">
                     <p class="h5 mt-3"><i class="bi bi-person-circle"></i> {{user.first_name}} {{user.last_name}}</p>
                     <p class="h5 mt-3"><i class="bi bi-envelope"></i> {{ user.email }}</p>
                     <p class="h5 mt-3"><i class="bi bi-telephone"></i> {{ user.username }}</p>
                     <a href="{% url 'edit_profile' %}">Настройки профиля</a>
                 </div>
                </div>
            </div>
            <table class="mt-4 table table-striped text-center">
                <thead>
                    <tr>
                        <th>Статус заказа</th>
                        <th>Название товара</th>
                        <th>Количество</th>
                        <th>Общая цена</th>
                    </tr>
                </thead>
                <tbody>
                        {% for u in user.order_set.all %}
                        <tr>
                            <td>
                                {% if u.status %}
                                        <p>{{u.status}}</p>
                                {% endif %}
                            </td>
                            <td class="product-title">
                                {% for i in u.productinorder_set.all %}
                                    <p>{{ i.product.title }}</p>
                                {% endfor %}
                            </td>
                            <td>
                                {% for i in u.productinorder_set.all %}
                                <span class="product-price">
                                    <p>{{ i.count }}</p>
                                </span>
                                {% endfor %}
                            </td>
                            <td>
                                <span class="total-product-in-cart-amount">
                                    <p>{{ u.total_price }} руб.</p>
                                </span>
                            </td>
                        </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>

        <a href="{% url 'logout' %}" class="login-button btn-danger" role="button">
                <i class="bi bi-box-arrow-left"></i> Выйти
        </a>
    </div>

{% endblock %}